name: Unplugin Example

on:
  push:
    branches: [main]

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@main

      - name: Build
        run: pnpm build

      - name: Install Example Dependencies & Build
        run: pnpm -C examples/vite run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/vite/dist
          force_orphan: true
